### PR TITLE
Issue #5

### PR DESCRIPTION
**Pull request by kotoshii**
- Add profile tab
- Add adaptive design:
  - Chat and profile tab are hidden in 'burger' on small screens
- Add room creation interface
- Tables are not used in rooms list
- Responsive interface elemets (bg-color, shadows on hover etc.)

### CODE REVIEW

**Comment by gurland** [comment]
Bug with scrollbar in auth window

default

**Comment by gurland** [comment]
Bug with submit button on Mozilla. I disabled `background-color: transparent` and it was somehow cured

default

**Comment by kotoshii** [comment]
Scroll bar is appearing while tapping on profile tab
image

**Comment by kotoshii** [comment]
Hovering enter-room button doesn't highlights it

**Comment by gurland** [comment]
Bug with transparent background on small width screens and also big top margin

image

**Pull request merged**
